# Generated by Django 3.0.2 on 2020-01-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20200123_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='avatar'),
        ),
    ]
