# Generated by Django 2.2.3 on 2020-01-23 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='alias',
        ),
    ]
