# Generated by Django 2.2.3 on 2020-01-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_usuario_alias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campeon',
            old_name='porcentajeDerrotas',
            new_name='porcentaje_derrotas',
        ),
        migrations.RenameField(
            model_name='campeon',
            old_name='porcentajeVictorias',
            new_name='porcentaje_victorias',
        ),
    ]
