# Generated by Django 2.2.3 on 2020-01-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20200125_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeon',
            name='popularidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campeon',
            name='porcentaje_derrotas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campeon',
            name='porcentaje_victorias',
            field=models.IntegerField(),
        ),
    ]
