# Generated by Django 2.2.3 on 2020-01-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20200125_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgCampeon',
        ),
        migrations.AddField(
            model_name='campeon',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='imgcampeon'),
        ),
    ]
