# Generated by Django 2.2.3 on 2020-01-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20200127_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campeon',
            old_name='avatar',
            new_name='imagen',
        ),
    ]
