# Generated by Django 2.2.3 on 2020-01-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20200127_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
        migrations.AddField(
            model_name='item',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='items'),
        ),
    ]
