# Generated by Django 2.2.3 on 2020-01-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_auto_20200127_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeon',
            name='imagen2',
            field=models.ImageField(default='default.png', upload_to='imgcampeon'),
        ),
        migrations.AddField(
            model_name='campeon',
            name='imagen3',
            field=models.ImageField(default='default.png', upload_to='imgcampeon'),
        ),
    ]
