# Generated by Django 2.2.3 on 2020-01-27 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_auto_20200127_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='camp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.Campeon'),
            preserve_default=False,
        ),
    ]
