# Generated by Django 2.2.3 on 2020-01-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_auto_20200127_2031'),
        ('usuario', '0003_auto_20200122_2252'),
    ]

    operations = [
    ]
